name: Continuous Integratin and deployment

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '5.0.x'

jobs:
  build: 
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Dotnet 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Start SQL Server (container)
        run: |
          docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Pass~w0r8' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest 

      - name: Sleep for some time 😴
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build App
        env:
          ConnectionStrings__DefaultConnecton: Server=localhost;Database=CiCdDemo_Tests;User=sa;Password=Pass~w0r8;
        run: dotnet build -c Release --no-restore
    
      - name: Run Tests
        run: dotnet test -c Release --no-build

      - name: Publish app
        run: dotnet publish -c Release -o ./out
